<?php
/**
 * Created by PhpStorm.
 * User: matas
 * Date: 11/4/17
 * Time: 2:29 PM
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
}
