services:
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
        arguments:
            - "@doctrine.orm.entity_manager"

    app.facebook_authenticator:
        class: AppBundle\Security\FacebookAuthenticator
        autowire: true

    AppBundle\EventListener\LoginEventListener:
        class: AppBundle\EventListener\LoginEventListener
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@KnpU\OAuth2ClientBundle\Client\ClientRegistry'
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }